import type { Profile, Conversation } from './types'

export const mockProfiles: Profile[] = [
  {
    id: '1',
    name: 'Sophia',
    age: 26,
    location: 'Miami, FL',
    category: 'Dating',
    photos: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=500&fit=crop'],
    rating: 5.0,
    reviewCount: 34,
    isVerified: true,
    isOnline: false,
    isFeatured: true,
    isFavorite: true,
    bio: 'Looking for genuine connections. Love travel and good conversations.',
    tags: ['Travel', 'Music', 'Fitness'],
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Valentina',
    age: 24,
    location: 'New York, NY',
    category: 'Companionship',
    photos: ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=500&fit=crop'],
    rating: 5.0,
    reviewCount: 19,
    isVerified: true,
    isOnline: true,
    isFeatured: false,
    isFavorite: false,
    bio: 'Sophisticated and fun. Perfect for events and dinners.',
    tags: ['Fine Dining', 'Art', 'Fashion'],
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    name: 'Jade',
    age: 23,
    location: 'Los Angeles, CA',
    category: 'Hookups',
    photos: ['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=500&fit=crop'],
    rating: 5.0,
    reviewCount: 52,
    isVerified: true,
    isOnline: false,
    isFeatured: true,
    isFavorite: false,
    bio: 'No strings attached. Here for a good time.',
    tags: ['Nightlife', 'Adventure', 'Spontaneous'],
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    name: 'Celeste',
    age: 28,
    location: 'Chicago, IL',
    category: 'Dating',
    photos: ['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=500&fit=crop'],
    rating: 4.0,
    reviewCount: 11,
    isVerified: true,
    isOnline: true,
    isFeatured: false,
    isFavorite: false,
    bio: 'Intelligent conversations and meaningful connections.',
    tags: ['Books', 'Wine', 'Philosophy'],
    createdAt: '2024-02-10',
  },
  {
    id: '5',
    name: 'Luna',
    age: 25,
    location: 'Austin, TX',
    category: 'Friendship',
    photos: ['https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=500&fit=crop'],
    rating: 4.5,
    reviewCount: 28,
    isVerified: true,
    isOnline: true,
    isFeatured: false,
    isFavorite: true,
    bio: 'Looking for genuine friendships and fun hangouts.',
    tags: ['Hiking', 'Coffee', 'Music'],
    createdAt: '2024-01-25',
  },
  {
    id: '6',
    name: 'Isabella',
    age: 27,
    location: 'Seattle, WA',
    category: 'Companionship',
    photos: ['https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop'],
    rating: 4.8,
    reviewCount: 45,
    isVerified: true,
    isOnline: false,
    isFeatured: true,
    isFavorite: false,
    bio: 'Elegant and charming. Perfect plus one for any occasion.',
    tags: ['Events', 'Travel', 'Luxury'],
    createdAt: '2024-02-05',
  },
]

export const mockConversations: Conversation[] = [
  {
    id: '1',
    participantId: '1',
    participantName: 'Sophia',
    participantPhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    lastMessage: 'Looking forward to meeting you!',
    lastMessageTime: '2 min ago',
    unreadCount: 1,
    isOnline: false,
  },
  {
    id: '2',
    participantId: '2',
    participantName: 'Valentina',
    participantPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
    lastMessage: 'That sounds great, let me know when works',
    lastMessageTime: '1 hour ago',
    unreadCount: 0,
    isOnline: true,
  },
  {
    id: '3',
    participantId: '3',
    participantName: 'Jade',
    participantPhoto: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop',
    lastMessage: 'Hey! Thanks for reaching out',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    isOnline: false,
  },
]
